### ISSUE TITLE
manual-auth-hook command "python3 validate.py" returned error code 1

### ISSUE THREAD

**Issue by philip-weiger** [steinsag/hosteurope-letsencrypt#11]
Hi! Thank you very much! This is a cool project.
So far, I could not make it work.
Do you know how to fix this?
(I put ***.de instead of my domain-)

```
sudo python3 neu.py
certbot certonly --manual --agree-tos -m zertifikat@***.de --preferred-challenge=http --manual-auth-hook "python3 validate.py" --staging -d www.***.de
Für diese Domains ein neues Zertifikat erstellen? (j/n): j
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Requesting a certificate for www.***.de
Performing the following challenges:
http-01 challenge for www.***.de
Running manual-auth-hook command: python3 validate.py
manual-auth-hook command "python3 validate.py" returned error code 1
Error output from manual-auth-hook command python3:
Traceback (most recent call last):
  File "validate.py", line 42, in <module>
    ftp.cwd('.well-known/acme-challenge')
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 621, in cwd
    return self.voidcmd(cmd)
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 282, in voidcmd
    return self.voidresp()
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 255, in voidresp
    resp = self.getresp()
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 250, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 .well-known/acme-challenge: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validate.py", line 45, in <module>
    ftp.mkd('.well-known')
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 633, in mkd
    resp = self.voidcmd('MKD ' + dirname)
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 282, in voidcmd
    return self.voidresp()
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 255, in voidresp
    resp = self.getresp()
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ftplib.py", line 250, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 .well-known: File exists

Waiting for verification...
Challenge failed for domain www.***.de
http-01 challenge for www.***.de
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.***.de
   Type:   unauthorized
   Detail: Invalid response from
   https://www.***.de/.well-known/acme-challenge/K7QyUEhlpApzu4UO6LZnpyuN_qGmjcbQ_QtRg5nca_Y
   [2a01:488:42:1000:b24d:768e:78:a085]: "<?xml version=\"1.0\"
   encoding=\"UTF-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0
   Strict//EN\"\n  \"http://www.w3.org/TR/xhtml1/D"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

I am very thankful if you can help me to fix this.

Philip

**Comment by steinsag** [comment]
To verify that you really own the domain, a file is uploaded so that let's encrypt service can download it. 

Uploading of this file fails. The file is normally uploaded to a folder .well-known/ in the root directory of your domain.

Judging from the exception, I think there is already a file with that name. Therefore the script is unable to create the folder. So make sure that no such file exists. Also make sure that your FTP account has the necessary access permissions to create folders and files.

**Comment by philip-weiger** [comment]
Yes, you are right. Thanks a lot. I deleted the .well-known folder that had been from a previous validation and then it worked.

**Comment by philip-weiger** [comment]
Still I have a problem when setting the certificate in the KIS. 
When Chromium tries to upload the files, it says "Ihre Datei wurde nicht gefunden" (file not found).

When I try to access the folder via console, I do not have access rights.
With `sudo su` I can access the folder and see, that the files exist. How can I make them accessible for the python script?

```
sudo python3 set_certificate.py
Password:
Traceback (most recent call last):
  File "set_certificate.py", line 16, in <module>
    cert_config = json.load(cert_conf_file)
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 141 (char 142)
```

**Comment by steinsag** [comment]
Now you got a problem / syntax error in your `cert-urls.json` file. I suggest you upload your cert manually.

**Comment by philip-weiger** [comment]
I am sorry... I had the syntax fixed.
The error is something else and I think I posted the wrong output in my last post. Sorry.

I try to decribe it better:
The script opens the right website in the browser.
I cannot upload the certificate manually, because I do not have permission to the folder.
This might also be the reason for "Ihre Datei wurde nicht gefunden" (file not found).

<img width="265" alt="Bildschirmfoto 2021-05-16 um 17 30 34" src="https://user-images.githubusercontent.com/46710670/118402941-73c5d400-b66c-11eb-8e6b-e2aad73c617e.png">
<img width="429" alt="Bildschirmfoto 2021-05-16 um 17 22 13" src="https://user-images.githubusercontent.com/46710670/118402944-76c0c480-b66c-11eb-937c-d8dd01c76287.png">

Thanks a lot for your help, @steinsag

**Comment by steinsag** [comment]
Mmmh, I think the problem might be that the upload process only works if you do the overall procedure without sudo. When I created the scripts many years ago, it was not possible to run certbot as non root user.

So you could try to run all commands to create cert and upload it without sudo. Hopefully, the output will be saved below your local home, where you have full access privileges.

**Comment by philip-weiger** [comment]
I could edit the rights with the macOS finder and make the files accessible.
But when I try to set the certificate automatically, Chromium still says "File not found"...
Somehow it seems to not find the right path.

Uploading manually works fine and the automated creation process already saves lots of time.
Thank you very much @steinsag ! :-)
