### ISSUE TITLE
set_certificate.py fails `TypeError: create_connection() got an unexpected keyword argument 'ping_interval'`

### ISSUE THREAD

**Issue by sarmbruster** [steinsag/hosteurope-letsencrypt#12]
First of all: thanks for that very helpful project :clap: 

Acquiring the certificates and validating them worked like a charm. However I do have issues setting the certifcates automatically. Latest pyppeteer (0.2.5) is installed. I'm getting:

```python3 set_certificate.py 
Traceback (most recent call last):
  File "set_certificate.py", line 72, in <module>
    asyncio.get_event_loop().run_until_complete(set_certificate())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "set_certificate.py", line 45, in set_certificate
    browser = await launch({'headless': False, 'slowMo': 1, 'devtools': True})
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/launcher.py", line 169, in launch
    self.connection = Connection(self.browserWSEndpoint, self._loop, connectionDelay, )
  File "/usr/local/lib/python3.8/dist-packages/pyppeteer/connection.py", line 43, in __init__
    self._ws = websockets.client.connect(
  File "/home/stefan/.local/lib/python3.8/site-packages/websockets/client.py", line 384, in __init__
    self._creating_connection = loop.create_connection(
TypeError: create_connection() got an unexpected keyword argument 'ping_interval'
```

Any idea, what's possibly wrong?

**Comment by steinsag** [comment]
Schwer zu sagen, klingt stark nach einem Problem mit den Python Abhängigkeiten. Ich würde es mit einer neuen virtualenv probieren, in der nur pypeteer per pip installiert wird. Besonders merkwürdig finde ich oben asyncio.
